### ISSUE TITLE
photo

### ISSUE THREAD

**Issue by c-LAzy** [c-LAzy/notes#1]
<img width="443" alt="image" src="https://user-images.githubusercontent.com/93063038/163178700-c33c6587-115c-4e44-be49-a5526c9f7c56.png">

**Comment by so1c** [comment]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/93063038/163182863-493b6f2f-7755-48bd-93e3-63285d68b3d1.png">

**Comment by so1c** [comment]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/93063038/163183370-5d7274ee-7dd9-432e-b8a9-884dbd8f20dc.png">
![image](https://user-images.githubusercontent.com/93063038/163183387-072af28e-a7d7-4f68-a4c5-7170e3a524f3.png)

**Comment by so1c** [comment]
![image](https://user-images.githubusercontent.com/93063038/163291208-ddd9bef5-7734-42ce-978f-f3f98b2cd225.png)

**Comment by c-LAzy** [comment]
![image](https://user-images.githubusercontent.com/93063038/163665429-095df1bd-6ac4-4023-a4e3-b58936722093.png)

**Comment by c-LAzy** [comment]
![image](https://user-images.githubusercontent.com/93063038/163666221-257ded9e-5809-4e48-bb2f-abc97f0ce6c7.png)

**Comment by c-LAzy** [comment]
![image](https://user-images.githubusercontent.com/93063038/163666250-5edb4b65-7d64-4cff-a5ed-83492325219d.png)

**Comment by c-LAzy** [comment]
[公式]

[公式]

**Comment by c-LAzy** [comment]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/93063038/163702132-5b2310db-95e7-459e-af1f-f44cd803eb3e.png">
